server:
  port: 8080
 
management:
  endpoint:
    health:
      probes:
        enabled: true
  
spring:
  servlet:    
    multipart:
      max-file-size: 3GB
      max-request-size: 3GB
     
analytics:
  host: localhost
  port: 5000

annotation:
  host: localhost
  port: 8081

organization:
  host: localhost
  port: 8082
    
storage:
  host: localhost
  port: 8083

job:
  host: localhost
  port: 8084
      
---

server:
  port: 8080
  
management:
  endpoint:
    health:     
      probes:
        enabled: true
              
spring:
  config:
    activate:
      on-profile: avib
  servlet:    
    multipart:
      max-file-size: 3GB
      max-request-size: 3GB
              
analytics:
  host: uniovi-avib-morphingprojections-backend-analytics
  port: 5000

annotation:
  host: uniovi-avib-morphingprojections-backend-annotation
  port: 8081
  
organization:
  host: uniovi-avib-morphingprojections-backend-organization
  port: 8082
  
storage:        
  host: uniovi-avib-morphingprojections-backend-storage
  port: 8083

job:
  host: uniovi-avib-morphingprojections-backend-job
  port: 8084