# Elasticsearch server connection from LOCAL device
server:
  port: 8080
 
management:
  endpoint:
    health:
      probes:
        enabled: true
            
# using ingress
#spring:
#  elasticsearch:
#    host: minikube.io
#    port: 443
#    pathPrefix: /elastic/
#    verifyHostnames: false
#    validateCertificates: false
#    username: elastic
#    password: password

# from using proxy port-forward  
spring:
  elasticsearch:
    host: localhost
    port: 9200
    pathPrefix: /
    verifyHostnames: false
    validateCertificates: false
    username: elastic
    password: password
    
# using proxy port-forward and a domain included in the certificate sign    
#spring:
#  elasticsearch:
#    host: avib-elastic
#    port: 9200
#    pathPrefix: /
#    verifyHostnames: false
#    validateCertificates: false
#    username: elastic
#    password: password

# using proxy port-forward and a domain included in the certificate sign    
#spring:
#  elasticsearch:
#    host: avispe.edv.uniovi.es
#    port: 443
#    pathPrefix: /kubernetes/elastic
#    verifyHostnames: false
#    validateCertificates: false
#    username: elastic
#    password: password

annotation:
  host: localhost
  port: 8081
  
analytics:
  host: localhost
  port: 5000
  
---

# Elasticsearch server connection from AVIB kubernetes cluster
server:
  port: 8080
  
management:
  endpoint:
    health:     
      probes:
        enabled: true
              
spring:
  config:
    activate:
      on-profile: avib
      
  elasticsearch:
    host: avib-elastic
    port: 9200
    pathPrefix: /
    verifyHostnames: false
    validateCertificates: false
    username: elastic
    password: password    

annotation:
  host: uniovi-avib-morphingprojections-backend-annotation
  port: 8081
      
analytics:
  host: uniovi-avib-morphingprojections-backend-analytics
  port: 5000
      
# using ingress
#spring:
#  config:
#    activate:
#      on-profile: avib
#      
#  elasticsearch:
#    host: avispe.edv.uniovi.es
#    port: 443
#    pathPrefix: /kubernetes/elastic/
#    verifyHostnames: false
#    validateCertificates: false
#    caFile: ca-elastic-avib.crt
#    username: elastic
#    password: password
